// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrhfqknvuvubudmzdbyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yaGZxa252dXZ1YnVkbXpkYnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTcwNjgsImV4cCI6MjA2OTczMzA2OH0.V--oNHW9570qfGg8jg9KY39i0EZTsBWksQREhfuJDHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});